name: Connect to Ubuntu VM (Self-Hosted Runner)

on:
  workflow_dispatch:

jobs:
  connect-to-vm:
    runs-on: [pranav-VirtualBox, self-hosted, Linux, X64]  # Ensure exact labels are matched

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load Config from config.env
        run: |
          # Source the config.env file to load environment variables
          source /home/pranav/actions-runner/config.env
          echo "Loaded configuration variables."

      - name: Check Runner IP (Self-Hosted)
        run: |
          # Now that the config.env is sourced, print the RUNNER_IP
          echo "Runner IP: $RUNNER_IP"  # Should show the value 192.168.1.3

      - name: Check File Existence
        run: |
          # Check if files in actions-runner directory exist
          echo "Checking files in the repository..."
          ls -la /home/pranav/actions-runner  # Adjust path if needed

      - name: Logs will generate now
        run: python3 path/to/generate_logs.py  # Adjust this path if necessary
