name: Test Self-Hosted Runner and Generate Logs

on:
  workflow_dispatch:

jobs:
  # Step 1: Test Self-Hosted Runner
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Test Runner Connection
        run: |
          echo "Testing runner connection..."
          echo "Runner is working!"

  # Step 2: Generate Logs with Python Script (Only if Step 1 succeeds)
  generate-logs:
    runs-on: [pranav-VirtualBox, self-hosted, Linux, X64]
    needs: test-runner

    steps:
      # Step 2.1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2.2: Verify Python Installation
      - name: Verify Python Installation
        run: python3 --version

      # Step 2.3: Run Python Script to Generate File
      - name: Run Python Script
        run: |
          echo "Running generate_logs.py..."
          python3 generate_logs.py

      # Step 2.4: Move Generated File to /home/pranav
      - name: Move Generated File to /home/pranav
        run: |
          echo "Checking if generated file exists..."
          if [ -f generated_file.txt ]; then
            echo "File found! Moving to /home/pranav..."
            mv generated_file.txt /home/pranav/
            echo "File moved successfully to /home/pranav"
          else
            echo "Error: generated_file.txt not found."
            exit 1
          fi
