name: Connect to Ubuntu VM (Self-Hosted Runner)

on:
  workflow_dispatch:

jobs:
  connect-to-vm:
    runs-on: [pranav-VirtualBox, self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Runner IP (Self-Hosted)
        run: |
          echo "Runner IP: $RUNNER_IP"  # Ensure this matches the value in your config.env

      - name: Check File Existence
        run: |
          echo "Checking files in the repository..."
          ls -la /home/pranav/actions-runner  # Adjust path if needed

      - name: Logs will generate now
        run: python3 path/to/generate_logs.py  # Adjust this path if necessary
