name: Connect to Ubuntu VM (Self-Hosted Runner)

on:
  workflow_dispatch:

jobs:
  connect-to-vm:
    runs-on: [pranav-VirtualBox, self-hosted, Linux, X64]  # Ensure exact labels are matched

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Check File Existence
        run: |
          # Check if files in actions-runner directory exist
          echo "Checking files in the repository..."
          ls -la /home/pranav/actions-runner  # Adjust path if needed

      - name: Logs will generate now
        run: python3 /home/pranav/Documents/generate_logs.py  # Adjust this path if necessary
