name: Generate Logs on VM

on:
  workflow_dispatch:

jobs:
  generate-logs:
    runs-on: self-hosted  # Use the self-hosted runner configured for the October repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install sshpass -y

    - name: Verify sshpass installation
      run: sshpass -V

    - name: Connect and Run Log Generation Script on VM
      run: |
        sshpass -p "Test@123" ssh -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -o LogLevel=ERROR \
        pranav@127.0.0.1 '
          echo "Connected to VM" &&
          uname -a &&
          python3 /home/pranav/actions-runner-October/_work/October/October/generate_logs.py
        '
