name: Create File on Ubuntu VM

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    name: Create a file on Ubuntu VM via SSH
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute SSH command on Ubuntu VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: 192.168.1.100
          username: pranav
          password: Test@123
          port: 22
          script: |
            echo "Hello from GitHub Actions" > /home/pranav/test_file.txt
            ls -l /home/pranav/test_file.txt
