name: Connect to Ubuntu VM (Self-Hosted Runner)

on:
  workflow_dispatch:

jobs:
  connect-to-vm:
    runs-on: [pranav-VirtualBox, self-hosted, Linux, X64]  # Ensures exact labels are matched

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify sshpass installation
        run: sshpass -V

      - name: Connect and Run Command on VM
        env:
          SSH_PASS: "Test@123"
        run: |
          echo "Starting SSH connection..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o LogLevel=ERROR \
          pranav@127.0.0.1 'echo "Connected to VM" && uname -a'

      - name: Check File Existence
        run: |
          echo "Checking files in the repository..."
          ls -la
          ls -la path/to/generate_logs.py  # Adjust this path if necessary

      - name: Logs will generate now
        run: python3 path/to/generate_logs.py  # Adjust this path if necessary
